Dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^users/', include('apps.users.urls',namespace='users')),
    url(r'^cart/', include('apps.cart.urls',namespace='cart')),
    url(r'^orders/', include('apps.orders.urls',namespace='orders')),
    url(r'^', include('apps.goods.urls',namespace='goods')),
    url(r'^tinymce',include('tinymce.urls')),
    url(r'^users/',include('apps.users.urls',namespace='users')) # 用户模块
]

apps/users/urls.py
from django.conf.urls import include, url

from apps.users import views

urlpatterns = [
    url(r'^register$',views.register,name='register'),
    url(r'^do_register$',views.do_register,name='do_register'),
    url(r'^active/(.+)$',views.ActiveView.as_view(),name='active'),
    url(r'^login$',views.LoginView.as_view(),name='login'),

]

templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css'%}">
</head>
<body>
	<div class="login_top clearfix">
		<a href="{% url 'index.html' %}" class="login_logo"><img src="{% url 'images/logo02.png' %} "></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="#">立即注册</a>
				</div>
				<div class="form_input">
					<form>
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">

{% load staticfiles %}

<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-注册</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png'%}"></a>
			<div class="reg_slogan">足不出户  ·  新鲜每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="#">登录</a>
			</div>
			<div class="reg_form clearfix">

				<form method="post" action="{% url 'users:register' %}">

					{% csrf_token %}

					<ul>
						<li>
							<label>用户名:</label>
							<input type="text" name="username" id="user_name">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>密码:</label>
							<input type="password" name="password" id="pwd">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>确认密码:</label>
							<input type="password" name="password2" id="cpwd">
							<span class="error_tip">提示信息</span>
						</li>
						<li>
							<label>邮箱:</label>
							<input type="text" name="email" id="email">
							<span class="error_tip">提示信息</span>
						</li>
						<li class="agreement">
							<input type="checkbox" name="allow" id="allow" checked="checked">
							<label>同意”天天生鲜用户使用协议“</label>
							<span class="error_tip2">提示信息</span>
						</li>
						<li class="reg_sub">
							<input type="submit" value="注 册" name="">
						</li>
					</ul>
				</form>
				<div style="color:red">{{ message }}</div>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>